apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-yanto
  labels:
    app: springboot-app-yanto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app-yanto
  template:
    metadata:
      labels:
        app: springboot-app-yanto
    spec:
      containers:
      - name: ct-app
        image: hikaruarch/springboot-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-yanto
  labels:
    app: springboot-app-yanto
spec:
  type: ClusterIP
  selector:
    app: springboot-app-yanto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-app-yanto
  labels:
    app: springboot-app-yanto
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hikaruarch.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springboot-app-yanto
            port:
              number: 80